Fix error handling logger method.
The error handler on dispatch is swallowing exceptions and never raising SerializationError due to "AttributeError: '_TxaioLogWrapper' object has no attribute 'failure'" being fired in the exception handling routine.